config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "main#index"

  get "/edit" => "main#edit"
  post "/edit" => "main#update"
  get "/more" => "range#new"
  post "/more" => "range#create"

  get "/login" => "session#new"
  post "/login" => "session#create"
  get "/logout" => "session#edit"
  post "/logout" => "session#destroy"

  get "/feed" => "main#feed", :format => false, :defaults => { format: "xml" }

  resource :credentials, only: [:edit, :update]

  resources :playdates, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post :prune
    end
    resources :availabilities, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :players, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/player.rb
# frozen_string_literal: true

require "digest/sha2"

class Player < ApplicationRecord
  has_many :availabilities, dependent: :destroy
  has_many :playdates, through: :availabilities, inverse_of: :players

  attribute :is_admin, default: false

  validates :name, presence: true
  validates :name, length: { minimum: 1 }
  validates :password, confirmation: true
  validates :name, uniqueness: true
  validates :password, length: { minimum: 5,
                                 if: proc { |user|
                                       user.password_hash.nil? or !user.password.to_s.empty?
                                     } }
  validates :is_admin, inclusion: [false, true]

  SALT = "change this to your own salt"

  default_scope { order(:abbreviation) }

  attr_reader :password

  def password=(pass)
    @password = pass
    return if pass.blank?

    self.password_hash = hash_password(pass, SALT)
    self.password_salt = SALT
  end

  def self.authenticate(name, pass)
    u = find_by(name:)
    u.nil? and return nil
    u.check_password(pass) or return nil
    u
  end

  def check_password(pass)
    password_hash == hash_password(pass, password_salt) or return nil
  end

  def availability_for_playdate(playdate)
    all_availabilities.find { _1.playdate_id == playdate.id }
  end

  def current_or_default_availability_for_playdate(playdate)
    availability_for_playdate(playdate) ||
      default_availability_for_playdate(playdate)
  end

  def default_availability_for_playdate(playdate)
    availabilities.build.tap do |av|
      av.playdate = playdate
      av.status = default_status || Availability::STATUS_MISSCHIEN
    end
  end

  private

  def all_availabilities
    @all_availabilities = availabilities
  end

  def hash_password(pass, salt)
    Digest::SHA256.hexdigest(pass + salt)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :authorize_admin

  def index
    @players = Player.paginate(page: params[:page])
  end

  def new
    @player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)
    @player.save
    respond_with @player, location: players_path
  end

  def update
    @player = Player.find(params[:id])
    @player.update player_params
    respond_with @player, location: players_path
  end

  def destroy
    @player = Player.find(params[:id])

    if @player == current_user
      flash[:alert] = t(".cannot_delete_self")
      redirect_to(players_url)
    else
      @player.destroy
      respond_with @player, location: players_path
    end
  end

  private

  def player_params
    params
      .expect(
        player: [:name,
          :full_name,
          :abbreviation,
          :is_admin,
          :default_status,
          :password,
          :password_confirmation]
      )
  end
end

app/views/players/_form_fields.html.erb
<label for="player[name]">Naam:</label>
<%= f.text_field :name %><br>

<label for="player[full_name]">Volledige naam:</label>
<%= f.text_field :full_name %><br>

<label for="player[abbreviation]">Afkorting:</label>
<%= f.text_field :abbreviation %><br>

<label for="player[password]">Password:</label>
<%= f.text_field :password %><br>

<label for="player[password_confirmation]">Password (nogmaals):</label>
<%= f.text_field :password_confirmation %><br>

<label for="player[is_admin]">Is Administrator:</label>
<%= select :player, :is_admin, [["Nee", false], ["Ja", true]] %><br>

<label for="player[default_status]">Standaardstatus:</label>
<%= select :player, :default_status, availability_options %><br>

app/views/players/edit.html.erb
<% content_for :page_title do %>
  Speler bewerken
<% end %>

<% if @player.errors.any? %>
  <div class="error_explanation">
    <h2><%= t("errors.template.header", model: "Speler", count: @player.errors.count) %></h2>
    <p><%= t("errors.template.body") %></p>

    <ul>
      <% @player.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@player) do |f| %>
  <p>
  <%= render "form_fields", f: f %>
  <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to "Tonen", @player %> | <%= link_to "Terug", players_path %>

app/views/players/index.html.erb
<% content_for :page_title do %>
  Spelers
<% end %>

<table>
  <tr>
    <th>Login</th>
    <th>Volledige naam</th>
    <th>Afkorting</th>
    <th>Admin?</th>
    <th>Standaardbeschikbaarheid</th>
    <th></th>
    <th></th>
  </tr>

  <% @players.each do |player| %>
    <tr>
      <td><%= h player.name %></td>
      <td><%= h player.full_name %></td>
      <td><%= h player.abbreviation %></td>
      <td><%= h player.is_admin %></td>
      <td><%= h status_display(player.default_status) %></td>
      <td class="action">
        <%= link_to "Bewerken", edit_player_path(player) %>
      </td>
      <td class="action">
        <% unless player == current_user %>
          <%= button_to "Destroy", player, form: { data: { turbo_confirm: "Are you sure?" } } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @players %>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<% content_for :page_title do %>
  Nieuwe speler
<% end %>

<% if @player.errors.any? %>
  <div class="error_explanation">
    <h2><%= t("errors.template.header", model: "Speler", count: @player.errors.count) %></h2>
    <p><%= t("errors.template.body") %></p>

    <ul>
      <% @player.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@player) do |f| %>
  <p>
  <%= render "form_fields", f: f %>
  <%= f.submit "Aanmaken" %>
  </p>
<% end %>

<%= link_to "Terug", players_path %>