config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "main#index"

  get "/edit" => "main#edit"
  post "/edit" => "main#update"
  get "/more" => "range#new"
  post "/more" => "range#create"

  get "/login" => "session#new"
  post "/login" => "session#create"
  get "/logout" => "session#edit"
  post "/logout" => "session#destroy"

  get "/feed" => "main#feed", :format => false, :defaults => { format: "xml" }

  resource :credentials, only: [:edit, :update]

  resources :playdates, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post :prune
    end
    resources :availabilities, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :players, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/availability.rb
# frozen_string_literal: true

class Availability < ApplicationRecord
  belongs_to :player
  belongs_to :playdate

  validates :playdate_id, uniqueness: { scope: [:player_id] }
  validates_associated :player, :playdate
  validates :status, inclusion: { in: 0..3 }

  STATUS_MISSCHIEN = 0
  STATUS_JA = 1
  STATUS_NEE = 2
  STATUS_HUIS = 3

  # TODO: Encapsulate these into methods
  VALUES = [STATUS_MISSCHIEN, STATUS_NEE, STATUS_JA, STATUS_HUIS].freeze
  LONG_DISPLAY = {
    STATUS_MISSCHIEN => "Misschien",
    STATUS_JA => "Ja",
    STATUS_NEE => "Nee",
    STATUS_HUIS => "Huis"
  }.freeze
  SHORT_DISPLAY = {
    STATUS_MISSCHIEN => "?",
    STATUS_JA => "+",
    STATUS_NEE => "−",
    STATUS_HUIS => "h"
  }.freeze
  def status_character
    # TODO: Deprecate?
    SHORT_DISPLAY[status]
  end
end

app/controllers/availabilities_controller.rb
# frozen_string_literal: true

# Administrative controller for editing availabilities.
class AvailabilitiesController < ApplicationController
  before_action :authorize_admin
  before_action :load_resource, only: [:edit, :update, :destroy]
  before_action :load_playdate, only: [:new, :create]

  def new
    @availability = Availability.new
  end

  def edit
    @player = @availability.player
  end

  def create
    @availability = @playdate.availabilities.build(new_availability_params)
    @availability.save
    respond_with @availability, location: playdate_path(@playdate)
  end

  def update
    @availability.update(edit_availability_params)
    respond_with @availability, location: playdate_path(@playdate)
  end

  def destroy
    @availability.destroy
    respond_with @availability, location: playdate_path(@playdate)
  end

  private

  def edit_availability_params
    params.expect(availability: [:status])
  end

  def new_availability_params
    params.expect(availability: [:player_id, :status])
  end

  def load_resource
    load_playdate
    @availability = @playdate.availabilities.find(params[:id])
  end

  def load_playdate
    @playdate = Playdate.find(params[:playdate_id])
  end
end

app/views/availabilities/edit.html.erb
<% content_for :page_title do -%>
  Editing availability
<% end -%>

<%= form_for [@playdate, @availability] do %>
  <p><label>Speler</label><br>
  <%= @player.full_name %></p>
  <p><label>Datum</label><br>
  <%= @playdate.day %></p>
  <p><label for="availability_status">Status</label><br>
  <%= select("availability", "status",
             Availability::VALUES.map { |v| [Availability::LONG_DISPLAY[v], v] }) %></p>

  <%= submit_tag "Save" %>
<% end %>

<%= button_to("Destroy", playdate_availability_path(@playdate, @availability),
              method: :delete,
              data: { turbo_confirm: "Are you sure you want to destroy this availability?" }) %>
<%= link_to "Back to list", playdate_path(@playdate) %>

app/views/availabilities/new.html.erb
<% content_for :page_title do %>
  New availability
<% end %>

<div class="content">
  <%= form_for [@playdate, @availability] do %>
    <% if @availability.errors.any? %>
      <div class="error_explanation">
        <h2><%= t("errors.template.header", model: "Speler", count: @availability.errors.count) %></h2>
        <p><%= t("errors.template.body") %></p>

        <ul>
          <% @availability.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p><label>Datum</label><br>
    <%= @playdate.day %></p>

    <p><label for="availability_player">Speler</label><br>
    <%= select("availability", "player_id",
               regular_players.map { |p| [p.name, p.id] }) %></p>

    <p><label for="availability_status">Status</label><br>
    <%= select("availability", "status",
               Availability::VALUES.map { |v| [Availability::LONG_DISPLAY[v], v] }) %></p>

    <%= submit_tag "Save" %>
  <% end %>

  <%= link_to "Back to list", playdate_path(@playdate) %>
</div>