config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "main#index"

  get "/edit" => "main#edit"
  post "/edit" => "main#update"
  get "/more" => "range#new"
  post "/more" => "range#create"

  get "/login" => "session#new"
  post "/login" => "session#create"
  get "/logout" => "session#edit"
  post "/logout" => "session#destroy"

  get "/feed" => "main#feed", :format => false, :defaults => { format: "xml" }

  resource :credentials, only: [:edit, :update]

  resources :playdates, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post :prune
    end
    resources :availabilities, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :players, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playdate! The Application - <%= controller_name %>: <%= action_name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="<%= url_for controller: "main", action: "feed", format: "xml" %>" rel="alternate" title="Atom" type="application/atom+xml">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="box" class="wrapper">
      <% if current_user %>
        <div class="logout">
          <p>Ingelogd als <%= h current_user.full_name %>.</p>
          <%= button_to "Uitloggen", logout_path %>
        </div>
      <% end %>

      <h1><%= yield :page_title %></h1>

      <div class="content">
        <%= render partial: "shared/showflash" %>
        <%= yield %>
        <% if current_user && current_user.is_admin? %>
          <p>
          <%= link_to "Speeldagen", controller: "playdates", action: "index" %>
          <%= link_to "Spelers", controller: "players", action: "index" %>
          <%= link_to "Hoofd", controller: "main", action: "index" %>
          </p>
        <% end %>
      </div>
      <% if current_user %>
        <p class="logout"><%= link_to "Wachtwoord wijzigen", edit_credentials_path %></p>
      <% end %>
    </div>
  </body>
</html>